"""Reusable scan conversion, slicing, and compositing utilities."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_LAZY_EXPORTS = {
    "CartesianGrid": ("echoxflow.scan.geometry", "CartesianGrid"),
    "CartesianImage": ("echoxflow.scan.conversion", "CartesianImage"),
    "BeamspacePixelGrid": ("echoxflow.scan.coordinates", "BeamspacePixelGrid"),
    "ImageLayer": ("echoxflow.scan.layers", "ImageLayer"),
    "Interpolation": ("echoxflow.scan.interpolation", "Interpolation"),
    "ScaleMarker": ("echoxflow.scan.matplotlib", "ScaleMarker"),
    "SectorDepthRuler": ("echoxflow.scan.matplotlib", "SectorDepthRuler"),
    "SectorDepthTick": ("echoxflow.scan.matplotlib", "SectorDepthTick"),
    "SectorGeometry": ("echoxflow.scan.geometry", "SectorGeometry"),
    "SectorLookup": ("echoxflow.scan.resampling", "SectorLookup"),
    "SlicePlane": ("echoxflow.scan.geometry", "SlicePlane"),
    "SphericalGeometry": ("echoxflow.scan.spherical", "SphericalGeometry"),
    "SphericalMosaic": ("echoxflow.scan.spherical", "SphericalMosaic"),
    "StitchedVolumeStack": ("echoxflow.scan.beat_stitching", "StitchedVolumeStack"),
    "VolumeGrid": ("echoxflow.scan.geometry", "VolumeGrid"),
    "VolumeSlice": ("echoxflow.scan.conversion", "VolumeSlice"),
    "CartesianPixelGrid": ("echoxflow.scan.coordinates", "CartesianPixelGrid"),
    "ContourGroupLayout": ("echoxflow.scan.contours", "ContourGroupLayout"),
    "ContourMaskResult": ("echoxflow.scan.contours", "ContourMaskResult"),
    "axial_slice_plane": ("echoxflow.scan.geometry", "axial_slice_plane"),
    "build_contour_masks": ("echoxflow.scan.contours", "build_contour_masks"),
    "clinical_spherical_mosaic": ("echoxflow.scan.spherical", "clinical_spherical_mosaic"),
    "compose_layers": ("echoxflow.scan.layers", "compose_layers"),
    "contour_group_layout_for_metadata": ("echoxflow.scan.contours", "contour_group_layout_for_metadata"),
    "draw_cm_marker": ("echoxflow.scan.matplotlib", "draw_cm_marker"),
    "draw_sector_depth_ruler": ("echoxflow.scan.matplotlib", "draw_sector_depth_ruler"),
    "layer_to_rgba": ("echoxflow.scan.layers", "layer_to_rgba"),
    "mesh_frame_indices_for_volume_timestamps": (
        "echoxflow.scan.beat_stitching",
        "mesh_frame_indices_for_volume_timestamps",
    ),
    "opacity_from_values": ("echoxflow.scan.layers", "opacity_from_values"),
    "physical_points_to_pixels": ("echoxflow.scan.geometry", "physical_points_to_pixels"),
    "points_to_sector_indices": ("echoxflow.scan.rasterization", "points_to_sector_indices"),
    "points_to_spherical_indices": ("echoxflow.scan.rasterization", "points_to_spherical_indices"),
    "prepare_3d_brightness_for_display": ("echoxflow.scan.beat_stitching", "prepare_3d_brightness_for_display"),
    "preconverted_spherical_mosaic": ("echoxflow.scan.spherical", "preconverted_spherical_mosaic"),
    "radial_slice_plane": ("echoxflow.scan.geometry", "radial_slice_plane"),
    "rasterize_beamspace_mask": ("echoxflow.scan.rasterization", "rasterize_beamspace_mask"),
    "rasterize_beamspace_volume_mask": ("echoxflow.scan.rasterization", "rasterize_beamspace_volume_mask"),
    "rasterize_polygon_pixels": ("echoxflow.scan.contours", "rasterize_polygon_pixels"),
    "rasterize_packed_mesh_volume_masks": ("echoxflow.scan.rasterization", "rasterize_packed_mesh_volume_masks"),
    "relative_qrs_trigger_times": ("echoxflow.scan.beat_stitching", "relative_qrs_trigger_times"),
    "relative_volume_timestamps": ("echoxflow.scan.beat_stitching", "relative_volume_timestamps"),
    "resample_sector": ("echoxflow.scan.resampling", "resample_sector"),
    "resample_sector_stack": ("echoxflow.scan.resampling", "resample_sector_stack"),
    "resize_pixel_xy": ("echoxflow.scan.coordinates", "resize_pixel_xy"),
    "sector_depth_ticks": ("echoxflow.scan.matplotlib", "sector_depth_ticks"),
    "sector_geometry_from_mapping": ("echoxflow.scan.geometry", "sector_geometry_from_mapping"),
    "sector_lookup": ("echoxflow.scan.resampling", "sector_lookup"),
    "sector_stack_to_cartesian": ("echoxflow.scan.conversion", "sector_stack_to_cartesian"),
    "sector_to_cartesian": ("echoxflow.scan.conversion", "sector_to_cartesian"),
    "set_cartesian_extent": ("echoxflow.scan.matplotlib", "set_cartesian_extent"),
    "spherical_depth_slice_stack": ("echoxflow.scan.spherical", "spherical_depth_slice_stack"),
    "spherical_geometry_from_metadata": ("echoxflow.scan.spherical", "spherical_geometry_from_metadata"),
    "spherical_radial_axis_stack": ("echoxflow.scan.spherical", "spherical_radial_axis_stack"),
    "stitch_3d_brightness_beats": ("echoxflow.scan.beat_stitching", "stitch_3d_brightness_beats"),
    "slice_volume": ("echoxflow.scan.conversion", "slice_volume"),
}


def __getattr__(name: str) -> Any:
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _LAZY_EXPORTS[name]
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value


__all__ = [
    "CartesianGrid",
    "CartesianImage",
    "BeamspacePixelGrid",
    "ImageLayer",
    "Interpolation",
    "ScaleMarker",
    "SectorDepthRuler",
    "SectorDepthTick",
    "SectorGeometry",
    "SectorLookup",
    "SlicePlane",
    "SphericalGeometry",
    "SphericalMosaic",
    "StitchedVolumeStack",
    "VolumeGrid",
    "VolumeSlice",
    "CartesianPixelGrid",
    "ContourGroupLayout",
    "ContourMaskResult",
    "axial_slice_plane",
    "build_contour_masks",
    "clinical_spherical_mosaic",
    "compose_layers",
    "contour_group_layout_for_metadata",
    "draw_cm_marker",
    "draw_sector_depth_ruler",
    "layer_to_rgba",
    "mesh_frame_indices_for_volume_timestamps",
    "opacity_from_values",
    "physical_points_to_pixels",
    "points_to_sector_indices",
    "points_to_spherical_indices",
    "prepare_3d_brightness_for_display",
    "preconverted_spherical_mosaic",
    "radial_slice_plane",
    "rasterize_beamspace_mask",
    "rasterize_beamspace_volume_mask",
    "rasterize_polygon_pixels",
    "rasterize_packed_mesh_volume_masks",
    "resample_sector",
    "resample_sector_stack",
    "resize_pixel_xy",
    "relative_volume_timestamps",
    "relative_qrs_trigger_times",
    "sector_depth_ticks",
    "sector_geometry_from_mapping",
    "sector_lookup",
    "sector_stack_to_cartesian",
    "sector_to_cartesian",
    "set_cartesian_extent",
    "spherical_depth_slice_stack",
    "spherical_geometry_from_metadata",
    "spherical_radial_axis_stack",
    "stitch_3d_brightness_beats",
    "slice_volume",
]
