"""Tools for reading and loading EchoXFlow echocardiographic data."""

from __future__ import annotations

from importlib import import_module
from typing import Any

from echoxflow.colors import (
    categorical_hex_color,
    categorical_hex_cycle,
    categorical_palette,
    data_modality_colormap_name,
    get_colors,
    load_colors,
    named_listed_colormap,
    neutral_categorical_hex,
    rgb_to_hex,
)
from echoxflow.config import data_root, load_settings, resolve_data_path
from echoxflow.croissant import (
    CroissantArrayRecord,
    CroissantCatalog,
    RecordingRecord,
    RecordingRelationship,
    croissant_path,
    find_derived_recordings,
    find_linked_recordings,
    find_recordings,
    find_source_recordings,
    linked_frame_timestamp_paths,
    load_croissant,
)
from echoxflow.export import (
    PredictionArray,
    PredictionManifest,
    RecordingArray,
    RecordingArrayEntry,
    build_prediction_manifest,
    prediction_array_entry,
    prediction_croissant_row,
    prediction_recording_record,
    recording_array_entry,
    recording_croissant_row,
    recording_link_croissant_rows,
    recording_record,
    replace_croissant_recording_links,
    upsert_croissant_recording,
    upsert_prediction_croissant_recording,
    write_prediction_manifest,
    write_prediction_recording,
    write_recording,
)
from echoxflow.loading import (
    LoadedArray,
    MeshFrame,
    PackedMeshAnnotation,
    RecordingStore,
    load_modality,
    load_modality_slice,
    load_stream,
    load_stream_slice,
    open_recording,
)
from echoxflow.objects import (
    AnnotationRef,
    ArrayRef,
    LinkedArray,
    MeshSequenceRef,
    RecordingObject,
    RecordingObjectKind,
    RecordingRef,
    StrainPanel,
    load_recording_object,
)
from echoxflow.spectral import SpectralCursorBox, SpectralMetadata, spectral_metadata_from_attrs
from echoxflow.streams import (
    AnnotationMaskStream,
    BrightnessModeStream,
    ColorDopplerPowerStream,
    ColorDopplerVelocityStream,
    EcgStream,
    EchoStream,
    FloatImageStream,
    GenericStream,
    MeshFaceStream,
    MeshFrameOffsetsStream,
    MeshPointStream,
    SpectralDopplerStream,
    StreamMetadata,
    TissueDopplerFloatStream,
    TissueDopplerRawStream,
    encode_tdi_linear_uint8_codes,
    encode_tdi_native_codes,
)

_LAZY_EXPORTS = {
    "CartesianGrid": ("echoxflow.scan.geometry", "CartesianGrid"),
    "CartesianImage": ("echoxflow.scan.conversion", "CartesianImage"),
    "ImageLayer": ("echoxflow.scan.layers", "ImageLayer"),
    "SectorGeometry": ("echoxflow.scan.geometry", "SectorGeometry"),
    "SlicePlane": ("echoxflow.scan.geometry", "SlicePlane"),
    "VolumeGrid": ("echoxflow.scan.geometry", "VolumeGrid"),
    "VolumeSlice": ("echoxflow.scan.conversion", "VolumeSlice"),
    "PlotStyle": ("echoxflow.plotting", "PlotStyle"),
    "RecordingPlotRenderer": ("echoxflow.plotting", "RecordingPlotRenderer"),
    "common_preview_arrays": ("echoxflow.preview", "common_preview_arrays"),
    "compose_layers": ("echoxflow.scan.layers", "compose_layers"),
    "opacity_from_values": ("echoxflow.scan.layers", "opacity_from_values"),
    "plot_recording": ("echoxflow.plotting", "plot_recording"),
    "rasterize_beamspace_mask": ("echoxflow.scan.rasterization", "rasterize_beamspace_mask"),
    "rasterize_beamspace_volume_mask": ("echoxflow.scan.rasterization", "rasterize_beamspace_volume_mask"),
    "rasterize_packed_mesh_volume_masks": ("echoxflow.scan.rasterization", "rasterize_packed_mesh_volume_masks"),
    "render_recording_frame": ("echoxflow.plotting", "render_recording_frame"),
    "render_recording_video": ("echoxflow.plotting", "render_recording_video"),
    "resample_sector": ("echoxflow.scan.resampling", "resample_sector"),
    "resample_sector_stack": ("echoxflow.scan.resampling", "resample_sector_stack"),
    "save_recording_plot": ("echoxflow.plotting", "save_recording_plot"),
    "sector_lookup": ("echoxflow.scan.resampling", "sector_lookup"),
    "sector_to_cartesian": ("echoxflow.scan.conversion", "sector_to_cartesian"),
    "slice_volume": ("echoxflow.scan.conversion", "slice_volume"),
    "write_preview_pair": ("echoxflow.preview", "write_preview_pair"),
    "write_preview_recording_video": ("echoxflow.preview", "write_preview_recording_video"),
}


def __getattr__(name: str) -> Any:
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _LAZY_EXPORTS[name]
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value


__all__ = [
    "AnnotationMaskStream",
    "AnnotationRef",
    "ArrayRef",
    "BrightnessModeStream",
    "CroissantCatalog",
    "CroissantArrayRecord",
    "ColorDopplerPowerStream",
    "ColorDopplerVelocityStream",
    "EcgStream",
    "EchoStream",
    "FloatImageStream",
    "GenericStream",
    "LinkedArray",
    "LoadedArray",
    "MeshFrame",
    "MeshFaceStream",
    "MeshFrameOffsetsStream",
    "MeshPointStream",
    "MeshSequenceRef",
    "PackedMeshAnnotation",
    "PredictionArray",
    "PredictionManifest",
    "RecordingArray",
    "RecordingArrayEntry",
    "RecordingObject",
    "RecordingObjectKind",
    "RecordingRef",
    "RecordingRecord",
    "RecordingRelationship",
    "RecordingStore",
    "SpectralCursorBox",
    "SpectralDopplerStream",
    "SpectralMetadata",
    "StrainPanel",
    "StreamMetadata",
    "TissueDopplerFloatStream",
    "TissueDopplerRawStream",
    "build_prediction_manifest",
    "categorical_hex_color",
    "categorical_hex_cycle",
    "categorical_palette",
    "common_preview_arrays",
    "croissant_path",
    "data_modality_colormap_name",
    "data_root",
    "encode_tdi_linear_uint8_codes",
    "encode_tdi_native_codes",
    "find_derived_recordings",
    "find_linked_recordings",
    "find_recordings",
    "find_source_recordings",
    "get_colors",
    "linked_frame_timestamp_paths",
    "load_croissant",
    "load_colors",
    "load_modality",
    "load_modality_slice",
    "load_recording_object",
    "load_stream",
    "load_stream_slice",
    "load_settings",
    "named_listed_colormap",
    "neutral_categorical_hex",
    "open_recording",
    "prediction_array_entry",
    "prediction_croissant_row",
    "prediction_recording_record",
    "recording_array_entry",
    "recording_croissant_row",
    "recording_link_croissant_rows",
    "recording_record",
    "replace_croissant_recording_links",
    "resolve_data_path",
    "rgb_to_hex",
    "spectral_metadata_from_attrs",
    "upsert_prediction_croissant_recording",
    "upsert_croissant_recording",
    "write_prediction_manifest",
    "write_prediction_recording",
    "write_preview_pair",
    "write_preview_recording_video",
    "write_recording",
]
